project:
  type: website

website:
  title: "Geospatial Analysis Practice Site"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - text: "Hands-on Exercises"
        menu: 
        - text: "Hands-on Exercise 1"
          href: hands-on-exercise/ex01/hands-on-ex01.qmd
      - text: "In-class Exercises"
        menu: 
        - text: "In-class Exercise 1"
          href: in-class-exercise/ex01/in-class-ex01.qmd
  search: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

