project:
  type: website

website:
  title: "IS415 Practice Site"
  search: true
  sidebar:
    style: "floating"
    contents:
      - text: "Home"
        href: "index.html"
      - text: "About"
        href: "about.html"
      - section: "Hands-on Exercises"
        contents: 
        - text: "01 ‘Geospatial Data Science with R’"
          href: "hands-on-exercise/ex01/hands-on-ex01.html"
        - text: "02 ‘Thematic Mapping and GeoVisualisation with R’"
          href: "hands-on-exercise/ex02/hands-on-ex02.html"
        - text: "03 ‘Spatial Point Pattern Analysis’"
          href: "hands-on-exercise/ex03/hands-on-ex03.html"
      - section: "In-class Exercises"
        contents: 
        - text: "Practice 01"
          href: "in-class-exercise/ex01/in-class-ex01.html"
        - text: "Practice 02"
          href: "in-class-exercise/ex02/in-class-ex02.html"

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

