project:
  type: website

website:
  title: "R for Geospatial Analytics"
  description: "A student's work on basic geospatial analyses"
  site-url: "https://smu-is415-kxheng-ay2024-25.netlify.app/"
  
  twitter-card:
    title: "R for Geospatial Analytics"
    description: "A student's work on basic geospatial analyses"
    card-style: "summary"
    
  open-graph:
    site-name: "R for Geospatial Analytics"
    description: "A student's work on basic geospatial analyses"
    locale: "en_GB"
  
  reader-mode: true
  bread-crumbs: true
  back-to-top-navigation: true
  page-navigation: true
  
  favicon: "images/logo.png"
  
  navbar:
    logo: "images/logo.png"
    search: true
    background: dark
    left:
      - text: "Home"
        href: "index.html"
      - text: "About"
        href: "about.html"
      - text: "Hands-on Exercises"
        href: "hands-on-exercise/hands-on-ex-intro.html"
      - text: "In-class Exercises"
        href: "in-class-exercise/in-class-ex-intro.html"
      - text: "Take Home Exercises"
        href: "take-home-exercise/take-home-ex-intro.html"

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - section: "Hands-on Exercises"
        contents:
        - text: "00 Hands-On Exercises Introduction"
          href: "hands-on-exercise/hands-on-ex-intro.html"
        - text: "01 ‘Geospatial Data Science with R’"
          href: "hands-on-exercise/ex01/hands-on-ex01.html"
        - text: "02 ‘Thematic Mapping and GeoVisualisation with R’"
          href: "hands-on-exercise/ex02/hands-on-ex02.html"
        - text: "03 (Part 1) ‘1st Order Spatial Point Pattern Analysis’"
          href: "hands-on-exercise/ex03/hands-on-ex03_01.html"
        - text: "03 (Part 2) ‘2nd Order Spatial Point Pattern Analysis’"
          href: "hands-on-exercise/ex03/hands-on-ex03_02.html"
        - text: "04 ‘Network Constrained Spatial Point Patterns Analysis’"
          href: "hands-on-exercise/ex04/hands-on-ex04.html"
        - text: "05 INCOMPLETE"
        - text: "06 (Part 1) ‘Global Measures of Spatial Autocorrelation’"
          href: "hands-on-exercise/ex06/hands-on-ex06_01.html"
        - text: "06 (Part 2) ‘Local Measures of Spatial Autocorrelation’"
          href: "hands-on-exercise/ex06/hands-on-ex06_02.html"
        - text: "07 ‘Geographical Segmentation with Spatially Constrained Clustering Techniques’"
          href: "hands-on-exercise/ex07/hands-on-ex07.html"
      - text: "---"
      - section: "In-class Exercises"
        contents:
        - text: "00 In-Class Exercises Introduction"
          href: "in-class-exercise/in-class-ex-intro.html"
        - text: "01 In-class Exercise 1 (Review)"
          href: "in-class-exercise/ex01/in-class-ex01.html"
        - text: "02 In-class Exercise 2 (Review)"
          href: "in-class-exercise/ex02/in-class-ex02.html"
        - text: "03 In-class Exercise 3 (Review)"
          href: "in-class-exercise/ex03/in-class-ex03.html"
        - text: "04 In-class Exercise 4 (Review)"
          href: "in-class-exercise/ex04/in-class-ex04.html"
        - text: "05 In-class Exercise 5 (Review)"
          href: "in-class-exercise/ex05/in-class-ex05.html"
        - text: "06 In-class Exercise 6 (Review)"
          href: "in-class-exercise/ex06/in-class-ex06.html"
      - text: "---"
      - section: "Take Home Exercises"
        contents:
        - text: "00 Take Home Exercise Introduction"
          href: "take-home-exercise/take-home-ex-intro.html"
        - text: "01 Take Home Exercise 1"
          href: "take-home-exercise/ex01/take-home-ex01.html"
        - text: "01 Take Home Exercise 2"
          href: "take-home-exercise/ex02/take-home-ex01.html"

  page-footer:
    background: "secondary"
    left: "Website by Heng Kuan Xin"
    right: "This website is built with [R](https://www.r-project.org/about.html), [Quarto](https://quarto.org/), [Netlify](https://www.netlify.com/).
      <br> Compass Icon created by [justicon](https://www.flaticon.com/free-icons/compass)"

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

