project:
  type: website

website:
  title: "IS415 Practice Site"
  search: true
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - section: "Hands-on Exercises"
        contents: 
        - text: "01 ‘Geospatial Data Science with R’"
          href: hands-on-exercise/ex01/hands-on-ex01.qmd
      - section: "In-class Exercises"
        contents: 
        - text: "Practice 01"
          href: in-class-exercise/ex01/in-class-ex01.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

